version: 1
update_configs:
  - package_manager: javascript
    directory: "/"
    update_schedule: monthly
    allowed_updates:
      - match:
          update_type: all
          dependency_type: direct
      - match:
          update_type: security
          dependency_type: indirect
